# Generated by Django 5.2.7 on 2025-11-09 03:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de Restablecimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('used', models.BooleanField(default=False, verbose_name='Token Usado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Restablecimiento',
                'verbose_name_plural': 'Tokens de Restablecimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('worker', 'Trabajador'), ('superadmin', 'Super Administrador')], default='worker', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol del Usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'users_userprofile',
            },
        ),
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], default='image', max_length=10, verbose_name='Tipo de Medio')),
                ('source_type', models.CharField(choices=[('camera', 'Cámara'), ('gallery', 'Galería')], default='gallery', max_length=10, verbose_name='Fuente del Medio')),
                ('media_source', models.CharField(blank=True, choices=[('camera', 'Cámara'), ('gallery', 'Galería')], default='gallery', max_length=10, null=True, verbose_name='Fuente del Medio (Frontend)')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='analysis/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen Original')),
                ('original_video', models.FileField(blank=True, null=True, upload_to='analysis/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])], verbose_name='Video Original')),
                ('processed_image_url', models.URLField(blank=True, null=True, verbose_name='URL Imagen Procesada')),
                ('processed_video_url', models.URLField(blank=True, null=True, verbose_name='URL Video Procesado')),
                ('total_lemons_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Limones Detectados')),
                ('lemon_count', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conteo de Limones (Legacy)')),
                ('count', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conteo Alternativo')),
                ('lemons_count', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conteo Limones Alt')),
                ('unripe_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limones Verdes')),
                ('semi_ripe_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limones Semi-maduros')),
                ('ripe_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limones Maduros')),
                ('overripe_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limones Sobre-maduros')),
                ('detection_confidence', models.FloatField(blank=True, help_text='Valor entre 0 y 1 indicando la confianza del modelo', null=True, verbose_name='Confianza Promedio de Detección')),
                ('hf_confidence_score', models.FloatField(default=0.0, help_text='Confianza como porcentaje desde Hugging Face', verbose_name='Puntuación de Confianza HF (%)')),
                ('processing_time', models.FloatField(default=0.0, help_text='Tiempo en segundos', verbose_name='Tiempo de Procesamiento')),
                ('model_type', models.CharField(default='huggingface', help_text='Modelo usado para la detección', max_length=50, verbose_name='Tipo de Modelo')),
                ('analysis_duration', models.DurationField(blank=True, help_text='Tiempo que tomó procesar el análisis', null=True, verbose_name='Duración del Análisis')),
                ('analysis_metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional como coordenadas de detección, configuración del modelo, etc.', verbose_name='Metadatos del Análisis')),
                ('detected_lemons', models.JSONField(blank=True, default=list, help_text='Array JSON con coordenadas y detalles de cada limón detectado', verbose_name='Detecciones de Limones')),
                ('annotated_image', models.TextField(blank=True, help_text='Imagen con bounding boxes en formato base64', null=True, verbose_name='Imagen Anotada Base64')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Análisis',
                'verbose_name_plural': 'Registros de Análisis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_analy_user_id_15e55b_idx'), models.Index(fields=['media_type', 'source_type'], name='users_analy_media_t_a165ea_idx'), models.Index(fields=['total_lemons_count'], name='users_analy_total_l_68f6e8_idx'), models.Index(fields=['created_at'], name='users_analy_created_3cab27_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkerAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre identificador del worker (ej: "Worker-001", "Tablet-Campo-A")', max_length=100, verbose_name='Nombre/Descripción')),
                ('key_prefix', models.CharField(editable=False, help_text='Primeros caracteres de la key para identificación', max_length=20, unique=True, verbose_name='Prefijo de Key')),
                ('key_hash', models.CharField(editable=False, help_text='Hash SHA-256 de la API key completa', max_length=128, unique=True, verbose_name='Hash de Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivado, la key no funcionará aunque sea válida', verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'API Key de Worker',
                'verbose_name_plural': 'API Keys de Workers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash'], name='users_worke_key_has_40ea24_idx'), models.Index(fields=['key_prefix'], name='users_worke_key_pre_889b96_idx'), models.Index(fields=['is_active', 'last_used_at'], name='users_worke_is_acti_8b1e90_idx')],
            },
        ),
    ]
