# Generated by Django 5.2.7 on 2025-11-10 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_device_activation',
            field=models.DateTimeField(blank=True, help_text='Última vez que se activó un dispositivo para este worker', null=True, verbose_name='Última Activación de Dispositivo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_configured',
            field=models.BooleanField(default=False, help_text='True si el trabajador tiene un PIN configurado', verbose_name='PIN Configurado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_hash',
            field=models.CharField(blank=True, help_text='Hash SHA-256 del PIN del trabajador (4-6 dígitos)', max_length=128, null=True, verbose_name='Hash de PIN'),
        ),
        migrations.CreateModel(
            name='ActivatedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ID único del dispositivo (ej: Android_Pixel6_1699...)', max_length=255, unique=True, verbose_name='ID del Dispositivo')),
                ('device_name', models.CharField(help_text='Nombre del dispositivo (ej: "Pixel 6 - Android")', max_length=255, verbose_name='Nombre del Dispositivo')),
                ('device_token', models.CharField(help_text='Token único generado para este dispositivo', max_length=128, unique=True, verbose_name='Token del Dispositivo')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, el dispositivo puede hacer login offline', verbose_name='Activo')),
                ('activated_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de activación', verbose_name='Fecha de Activación')),
                ('last_used', models.DateTimeField(blank=True, help_text='Última vez que se usó este dispositivo', null=True, verbose_name='Último Uso')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Fecha y hora de desactivación (si aplica)', null=True, verbose_name='Fecha de Desactivación')),
                ('platform', models.CharField(blank=True, help_text='Plataforma del dispositivo (Android/iOS)', max_length=50, null=True, verbose_name='Plataforma')),
                ('app_version', models.CharField(blank=True, help_text='Versión de la app al momento de activación', max_length=20, null=True, verbose_name='Versión de la App')),
                ('worker', models.ForeignKey(help_text='Trabajador propietario de este dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='activated_devices', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Dispositivo Activado',
                'verbose_name_plural': 'Dispositivos Activados',
                'ordering': ['-activated_at'],
                'indexes': [models.Index(fields=['worker', 'is_active'], name='users_activ_worker__60f142_idx'), models.Index(fields=['device_id'], name='users_activ_device__8edbb5_idx'), models.Index(fields=['device_token'], name='users_activ_device__c510f6_idx')],
            },
        ),
    ]
