# Generated by Django 5.2.7 on 2025-11-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_last_device_activation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrecord',
            name='analysis_duration',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='count',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='hf_confidence_score',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='lemon_count',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='lemons_count',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='media_source',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='original_video',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='overripe_count',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='processed_video_url',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='ripe_count',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='semi_ripe_count',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='unripe_count',
        ),
        migrations.AlterField(
            model_name='analysisrecord',
            name='model_type',
            field=models.CharField(default='tensorflow_lite', help_text='Modelo usado para la detección', max_length=50, verbose_name='Tipo de Modelo'),
        ),
    ]
