# Generated by Django 5.2.7 on 2025-11-11 22:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='True si el usuario debe cambiar su contraseña en el próximo login', verbose_name='Cambio de Contraseña Requerido'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Identificador único para URLs', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin que creó este usuario (solo para workers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organización a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='users.organization', verbose_name='Organización'),
        ),
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Formato internacional: +56912345678', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono debe tener formato internacional (ej: +56912345678)', regex='^\\+?1?\\d{8,15}$')], verbose_name='Teléfono')),
                ('organization_name', models.CharField(max_length=100, verbose_name='Nombre de Organización')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Razón de Rechazo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Solicitud')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_request', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creado')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admin_requests', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Administrador',
                'verbose_name_plural': 'Solicitudes de Administradores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='users_admin_email_72b525_idx'), models.Index(fields=['status', '-created_at'], name='users_admin_status_4c345e_idx')],
            },
        ),
    ]
