# Generated by Django 5.2.7 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_password_change_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key_short',
            field=models.CharField(blank=True, db_index=True, help_text='API Key corta para autenticación offline (formato: AGR-WK-XXXXXX)', max_length=13, null=True, unique=True, verbose_name='API Key Simple'),
        ),
    ]
