# Generated by Django 5.2.7 on 2025-11-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Agrega constraint de unicidad al campo email del modelo User.

    IMPORTANTE: Esta migración asume que ya NO hay emails duplicados en la DB.
    Si hay duplicados, ejecutar fix_duplicate_email.py antes de aplicar esta migración.
    """

    dependencies = [
        ('users', '0007_userprofile_api_key_short'),
    ]

    operations = [
        # Agregar índice único al campo email usando RunSQL
        # No podemos usar AlterField porque User es de django.contrib.auth, no de users
        migrations.RunSQL(
            # SQL para agregar el constraint de unicidad
            sql=[
                """
                CREATE UNIQUE INDEX IF NOT EXISTS auth_user_email_unique
                ON auth_user (email);
                """,
            ],
            # SQL para revertir (DROP INDEX)
            reverse_sql=[
                "DROP INDEX IF EXISTS auth_user_email_unique;",
            ],
        ),
    ]
