# Generated by Django 5.2.7 on 2025-11-17 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_unique_email_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='photo_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de foto dentro de la sesión (1, 2, 3, 4, 5, 6, ...)', verbose_name='Número de Foto'),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID de la sesión local del mobile (agrupa 6+ fotos del mismo árbol)', max_length=255, null=True, verbose_name='ID de Sesión'),
        ),
        migrations.AddIndex(
            model_name='analysisrecord',
            index=models.Index(fields=['session_id', 'photo_number'], name='users_analy_session_b8f93a_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrecord',
            index=models.Index(fields=['user', 'session_id'], name='users_analy_user_id_30c93c_idx'),
        ),
    ]
