# Generated by Django 5.2.7 on 2025-11-18 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_analysisrecord_photo_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='posicion',
            field=models.PositiveIntegerField(default=1, verbose_name='Posición/Árbol en Hilera'),
        ),
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Cuartel')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuarteles', to='users.organization')),
            ],
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='cuartel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cuartel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cuartel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cuartel', verbose_name='Cuartel Asignado'),
        ),
        migrations.CreateModel(
            name='Hilera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Hilera')),
                ('cuartel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hileras', to='users.cuartel')),
            ],
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='hilera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hilera'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hilera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hilera', verbose_name='Hilera Asignada'),
        ),
    ]
