# Generated by Django 5.2.7 on 2025-11-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_analysisrecord_posicion_cuartel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cuartel',
        ),
        migrations.RemoveField(
            model_name='hilera',
            name='cuartel',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='cuartel',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hilera',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='hilera',
        ),
        migrations.RemoveField(
            model_name='analysisrecord',
            name='posicion',
        ),
        migrations.DeleteModel(
            name='Cuartel',
        ),
        migrations.DeleteModel(
            name='Hilera',
        ),
    ]
